

[package]
name = "codama-renderers-vixen-parser-e2e-meteora"
version = "0.0.0"
edition = "2021"


[dependencies]
prost = "0.13.1"
yellowstone-vixen-core = { git = "https://github.com/rpcpool/yellowstone-vixen", branch = "main",features = ["proto"]}
tonic = { version = "0.12.1", features = ["gzip", "zstd"] }
solana-program = "^2.1.6"
borsh = "^0.10"
codama-renderers-rust-e2e-meteora = { path = "../../../../renderers-rust/e2e/meteora" }



[build-dependencies]
prost-build = "0.13.1"

