[package]
name = "codama-renderers-vixen-parser-e2e-meteora"
version = "0.0.0"
edition = "2021"


[dependencies]
yellowstone-vixen-core = { git = "https://github.com/rpcpool/yellowstone-vixen", branch = "main" }
codama-renderers-rust-e2e-meteora = { path = "../../../renderers-rust/e2e/meteora" }
solana-program = "^2.1.6"
borsh = "^0.10"
