[package]
name = "codama-vixen-parser-test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo", "wrap_help"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
yellowstone-vixen = { git = "https://github.com/rpcpool/yellowstone-vixen", branch = "main" }

codama-renderers-vixen-parser-e2e-system = { path = "../system_parser" }
codama-renderers-vixen-parser-e2e-memo = { path = "../memo_parser" }
codama-renderers-vixen-parser-e2e-anchor = { path = "../anchor_parser" }
